[project]
name = "hericendre"
version = "0.1.0"
description = "A radioactive decay and fuel depletion code"
readme = "README.md"
authors = [{ name = "Nicolas Linden", email = "nicolas@nlinden.com" }]
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.13.0",
    "numpy>=2.2.4",
    "pint>=0.24.4",
    "polars>=1.26.0",
]

[project.scripts]
hericendre = "hericendre:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
