name: Build Héricendre

on:
  push:
    branches: [CI]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4
      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.23.2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

          
