name: Build Héricendre

on:
  push:
    branches: [CI]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "macos-13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Build Package
        run: |
          apt update -y && apt install -y cmake
          export VCPKG_CMAKE="$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"
          export VCPKG_ROOT="$(pwd)/vcpkg/"
          python -m pip install --upgrade build
          python -m build -Ccmake.define.CMAKE_TOOLCHAIN_FILE=$VCPKG_CMAKE


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: wheel-artifacts
          path: dist/*.whl

  upload:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Upload wheels to PyPI
        uses: actions/download-artifact@v4
        with:
          name: wheel-artifacts
          path: dist

      - name: List downloaded artifacts
        run: ls -lah dist
          
