name: Build Héricendre

on:
  push:
    branches: [CI]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo "$(pwd)/vcpkg" >> $GITHUB_PATH
          export VCPKG_CMAKE=vcpkg/scripts/buildsystems/vcpkg.cmake
          ls $VCPKG_CMAKE

      - name: Install C++ Dependencies
        run: |
          ./vcpkg/vcpkg install highfive
          ./vcpkg/vcpkg install eigen3
          ./vcpkg/vcpkg install fmt
          ./vcpkg/vcpkg install pugixml
          ./vcpkg/vcpkg install tomlplusplus

      - name: Build Package
        run: |
          uv build -Ccmake.define.CMAKE_TOOLCHAIN_FILE=$VCPKG_CMAKE
          ls dist
